---
title: "Untitled"
output: html_document
---

```{r}
# file paths, custom fucntions and packages
scripts <- 'C:/Users/tommy/Google Drive/Coursework/1machine_learning/scripts/'
data <- "C:/Users/tommy/Google Drive/Coursework/1machine_learning/data/"
raw <- "C:/Users/tommy/Google Drive/Coursework/1machine_learning/data/raw/"
source(paste0(scripts,'helper_functions.R'))
LoadPackages(c("dplyr", "ggplot2", "caret", "tibble", 'Boruta', 'stringr'))
```

```{r}
submit_data <- readRDS(paste0(data,"submit_data.rds"))
train <- readRDS(paste0(data,"train.rds")) %>% select(-id, -set)
test <- readRDS(paste0(data,"test.rds"))
```

```{r}
#  create list with indexes for each cv fold
set.seed(888)
cv_folds <- createFolds(train$target, k = 5, list = TRUE, returnTrain = TRUE)
```


```{r}
ctrl <- trainControl(method = "cv", index = cv_folds, savePredictions = 'final',
                     verboseIter = T)
```

```{r}
set.seed(888)
rf_grid <- expand.grid(mtry = c(2,5,9,12), 
                       min.node.size = c( 60, 80, 85, 90, 100),
                       splitrule = c("variance", 'extratrees'))

rf <- train(target ~ ., data = train, tuneGrid = rf_grid, num.tree = 1000, 
            importance = 'permutation', metric = "MAE", method = "ranger", 
            trControl = ctrl)

rf$results %>% arrange(MAE)

saveRDS(rf, paste0(data, "rf.rds"))


set.seed(888)
enet_grid <- expand.grid(alpha = seq(0,1, length = 15), 
                          lambda = c(seq(0.0001, 1, length =  300),
                                     seq(1,5, length = 20))) %>%
  sample_frac(.2) 

enet <- train(target ~ . , data = train, tuneGrid = enet_grid,
                preProcess = c("center", "scale"), metric = "MAE",
                method = "glmnet", trControl = ctrl)

enet$results %>% arrange(MAE)

# var imp
enet_coef <- coef(enet$finalModel, enet$bestTune$lambda) %>% 
  as.matrix() %>% as.data.frame() %>% rownames_to_column("feat")
names(enet_coef) <- c("feat", "coef")
enet_fit_coef %>% arrange(desc(abs(coef)))


saveRDS(enet, paste0(data, "enet.rds"))

```





```{r}


set.seed(888)
svm_grid <- expand.grid(sigma = 2^seq(-10, -7, length = 12), 
                        C = seq(.8, 1.5, by = .1))

svm <- train(target ~ ., data = train, tuneGrid = svm_grid,
             metric = "MAE", method = "svmRadial", 
            preProcess = c("center", "scale"), trControl = ctrl)

svm$results %>% arrange(MAE)

saveRDS(svm, paste0(data, "svm.rds"))
```


```{r}
set.seed(888)
knn_grid <- expand.grid(k = seq(10,120, by = 5))

knn <- train(target ~ ., data = train, tuneGrid = knn_grid,
             metric = "MAE", method = "knn", 
            preProcess = c("center", "scale"), trControl = ctrl)

knn$results %>% arrange(MAE)

saveRDS(knn, paste0(data, "knn.rds"))
```


```{r}
set.seed(888)
xgb_grid <- expand.grid(nrounds = c(50, 100, 150), 
                        max_depth = c(2, 5, 10, 15), 
                        eta = seq(.01,.3, by = .04), 
                        gamma = c(0, 1, 3), 
                        colsample_bytree = c(.5, .7, .9), 
                        min_child_weight = seq(5, 55, by = 10), 
                        subsample = c(.5, .7, .9)) %>%
  sample_frac(.06)

xgb <- train(target ~ ., data = train, tuneGrid = xgb_grid,
             metric = "MAE", method = "xgbTree",trControl = ctrl)

xgb$results %>% arrange(MAE)

saveRDS(xgb, paste0(data, "xgb.rds"))
```

```{r}
set.seed(888)
icr <- train(target ~ . , data = train, tuneLength = 20,
                    metric = "MAE", method = "icr", 
                    preProcess = c("center", "scale"), trControl = ctrl)

icr$results %>% arrange(MAE)
```


```{r}
set.seed(888)
ppr <- train(target ~ . , data = train, tuneLength = 20,
                    metric = "MAE", method = "ppr", 
                    preProcess = c("center", "scale"), trControl = ctrl)

ppr$results %>% arrange(MAE)
```


```{r}
set.seed(888)
bagEarth <- train(target ~ . , data = train, tuneLength = 20,
                    metric = "MAE", method = "bagEarth", 
                    preProcess = c("center", "scale"), trControl = ctrl)

bagEarth$results %>% arrange(MAE)
```

```{r}
set.seed(888)
cubist <- train(target ~ . , data = train, tuneLength = 20,
                    metric = "MAE", method = "cubist", 
                    preProcess = c("center", "scale"), trControl = ctrl)

cubist$results %>% arrange(MAE)
```

```{r}
null <- train(target ~ . , data = train, 
                    metric = "MAE", method = "null", trControl = ctrl)

null$results %>% arrange(MAE)
```



Model stack
```{r}
rf_oos <- rf$pred %>% arrange(rowIndex) %>% pull(pred)
enet_oos <- enet$pred %>% arrange(rowIndex) %>% pull(pred)
svm_oos <- svm$pred %>% arrange(rowIndex) %>% pull(pred)
knn_oos <- knn$pred %>% arrange(rowIndex) %>% pull(pred)
xgb_oos <- xgb$pred %>% arrange(rowIndex) %>% pull(pred)
icr_oos <- icr$pred %>% arrange(rowIndex) %>% pull(pred)
ppr_oos <- ppr$pred %>% arrange(rowIndex) %>% pull(pred)
bagEarth_oos <- bagEarth$pred %>% arrange(rowIndex) %>% pull(pred)
cubist_oos <- cubist$pred %>% arrange(rowIndex) %>% pull(pred)

train_stack <- data.frame(target = train$target,
                          rf_oos = rf_oos,
                          enet_oos = enet_oos,
                          svm_oos = svm_oos,
                          knn_oos = knn_oos,
                          xgb_oos = xgb_oos,
                          icr_oos = icr_oos,
                          ppr_oos = ppr_oos,
                          bagEarth_oos = bagEarth_oos,
                          cubist_oos = cubist_oos)

cor(train_stack)

train_stack <- train_stack %>% select(-rf_oos)
```




```{r}
set.seed(888)
xgb_stack <- train(target ~ ., data = train_stack, tuneGrid = xgb_grid,
             metric = "MAE", method = "xgbTree",trControl = ctrl)

xgb_stack$results %>% arrange(MAE)
```


```{r}
svm$pred %>%
  select(rowIndex, pred, Resample) %>%
  rename(predection = pred, holdout = Resample) %>% 
  mutate(trained_on = case_when(holdout == "Fold1" ~ "Folds 2, 3, 4, 5",
                                holdout == "Fold2" ~ "Folds 1, 3, 4, 5", 
                                holdout == "Fold3" ~ "Folds 1, 2, 4, 5", 
                                holdout == "Fold4" ~ "Folds 1, 2, 3, 5", 
                                holdout == "Fold5" ~ "Folds 1, 2, 3, 4")) %>% 
  arrange(rowIndex)


svm$pred

cv_folds$Fold1 %>% as.data.frame()
```

```{r}
foo2 <- enet_fit$pred %>%
  select(rowIndex, pred, Resample) %>% filter(Resample == "Fold5")
```


```{r}
train %>% rownames_to_column("index") %>% arrange(index)
```



```{r}
foo <- cv_folds$Fold1 %>% as.data.frame()

names(foo) <- "foo"

foo %>% filter(foo %in% c(855))
```

```{r}
pred <- predict(xgb, test)

MAE(pred, test$target)
```

```{r}
ts2
```

```{r}
corrplot(cor(ts2 %>% select(-target)), method = 'circle',
         type = 'upper', tl.col = "black", tl.srt = 45)

ts2
```

